apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: gos
    app: hero
    version: v1-native
  name: hero-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hero
      version: v1-native
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
      labels:
        project: gos
        app: hero
        version: v1-native
    spec:
      containers:
      - image: localhost:5000/jotak/gos-hero-native:dev
        imagePullPolicy: IfNotPresent
        name: hero-native
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.kafka:9092
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: hero
  labels:
    project: gos
    app: hero
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: hero
