apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: gos
    app: hero
    version: v1
  name: hero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hero
      version: v1
  template:
    metadata:
      labels:
        project: gos
        app: hero
        version: v1
    spec:
      containers:
      - image: localhost:5000/jotak/gos-hero-hotspot:dev
        imagePullPolicy: IfNotPresent
        name: hero
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.kafka:9092
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hero
  labels:
    project: gos
    app: hero
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: hero
