apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: gos
    type: game-object
    app: hero
    version: base
  name: hero
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hero
      version: base
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
      labels:
        project: gos
        type: game-object
        app: hero
        version: base
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: hero
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.kafka:9092
        - name: ARROW_API_MP_REST_URL
          value: http://arrow:8080
        - name: USE_BOW
          value: "true"
        - name: RUNTIME
          value: "quarkus-hotspot"
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: hero
  labels:
    project: gos
    type: game-object
    app: hero
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: hero
