apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: gos
    app: web
    version: v1
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        project: gos
        app: web
        version: v1
    spec:
      containers:
      - image: localhost:5000/jotak/gos-web-hotspot:dev
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.kafka:9092
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    project: gos
    app: web
spec:
  ports:
    - name: http
      port: 8081
  selector:
    app: web
